FROM golang:@@golang@@-alpine@@alpine@@ as builder
ENV KRAKEND_DOWNLOAD_SHA512 @@sha512sum@@
WORKDIR /app

RUN apk add --no-cache make gcc musl-dev gnupg
RUN set -eux; \
    wget -O krakend.tar.gz "https://github.com/devopsfaith/krakend-ce/archive/refs/tags/v@@version@@.tar.gz"; \
    wget -O krakend.tar.gz.asc "https://github.com/devopsfaith/krakend-ce/releases/download/v@@version@@/v@@version@@.tar.gz.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 5B270F2E01E375FD9D5635E25DE6FD698AD6FDD2; \
    gpg --batch --verify krakend.tar.gz.asc krakend.tar.gz; \
    tar xzf krakend.tar.gz -C /app --strip-components 1; \
	echo "$KRAKEND_DOWNLOAD_SHA512 *krakend.tar.gz" | sha512sum -c;


RUN make build

FROM alpine:@@alpine@@

LABEL maintainer="community@krakend.io"
ENV VERSION="@@version@@"

RUN apk add --no-cache ca-certificates && \
	adduser -u 1000 -S -D -H krakend && \
	mkdir /etc/krakend && \
	echo '{ "version": @@config_version@@ }' > /etc/krakend/krakend.json

COPY --from=builder /app/krakend /usr/bin/krakend

USER 1000

WORKDIR /etc/krakend

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8080 8090
